eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
feign:
  hystrix:
   enabled: true
spring:
  cloud:
     bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,bus-env